import os, sys, tempfile, threading, json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(root))
state=Path(tempfile.mkdtemp(prefix='aistora-browser-state-'))
os.environ.update(PYTHON_DOTENV_DISABLED='1',PYTHONDONTWRITEBYTECODE='1',PIPELINE_ENABLED='false',GEMINI_API_KEY='',DATABASE_URL='sqlite:///'+(state/'test.db').as_posix(),UPLOAD_FOLDER=str(state/'uploads'),DATASET_CACHE_DIR=str(state/'cache'),SESSION_FILE_DIR=str(state/'sessions'),AGENT_CANCELLATION_DIR=str(state/'cancellations'),AGENT_AUDIT_PATH=str(state/'audit.jsonl'))
from app import app
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright, expect
app.config['LOGIN_ATTEMPTS_PER_MINUTE']=50
server=make_server('127.0.0.1',5067,app,threaded=True)
threading.Thread(target=server.serve_forever,daemon=True).start()
shots=Path(os.environ.get("AISTORA_SCREENSHOT_DIR", str(state / "screenshots")))
shots.mkdir(parents=True,exist_ok=True)
errors=[]
try:
    with sync_playwright() as p:
        browser=p.chromium.launch(channel='chrome',headless=True)
        page=browser.new_page(viewport={'width':1360,'height':900},device_scale_factor=1)
        page.on('pageerror', lambda err:errors.append(str(err)))
        page.goto('http://127.0.0.1:5067/app')
        expect(page.locator('#loading-overlay')).to_be_hidden()
        expect(page.locator('#auth-title')).to_have_text('Welcome back')
        page.screenshot(path=str(shots/'aistora-login-desktop.png'),full_page=True)
        page.locator('#auth-submit-btn').click()
        expect(page.locator('#auth-email-error')).to_be_visible()
        page.locator('#auth-toggle-mode').click()
        expect(page.locator('#auth-password')).to_have_attribute('autocomplete','new-password')
        page.locator('#auth-email').fill('smoke@example.com')
        page.locator('#auth-password').fill('launch-test-password')
        page.locator('#auth-password').press('Enter')
        expect(page.locator('#auth-error-title')).to_have_text('Account created')
        expect(page.locator('#auth-btn-label')).to_have_text('Sign in')
        page.locator('#auth-password').fill('wrong-password')
        page.locator('#auth-submit-btn').click()
        expect(page.locator('#auth-error-title')).to_have_text("We couldn't sign you in")
        page.wait_for_timeout(3300)
        expect(page.locator('#auth-error')).to_be_visible()
        page.screenshot(path=str(shots/'aistora-login-error.png'),full_page=True)
        page.locator('#auth-show-password').click()
        expect(page.locator('#auth-password')).to_have_attribute('type','text')
        page.locator('#auth-password').fill('launch-test-password')
        page.locator('#auth-password').press('Enter')
        expect(page.locator('#db-screen')).to_be_visible()
        page.locator('#create-db-btn').click()
        page.locator('#new-db-name').fill('Launch smoke test')
        page.locator('#confirm-db-btn').click()
        page.locator('.db-item-btn').filter(has_text='Launch smoke test').click()
        expect(page.locator('#upload-screen')).to_be_visible()
        expect(page.locator('#load-options')).to_be_hidden()
        expect(page.locator('#loads-section')).to_be_hidden()
        page.locator('#file-upload').set_input_files({'name':'sales.csv','mimeType':'text/csv','buffer':b'region,amount\nWest,10\nEast,20\nWest,30\n'})
        expect(page.locator('#file-list')).to_contain_text('sales')
        expect(page.locator('#go-chat')).to_be_enabled()
        page.locator('#go-chat').click()
        page.locator('#eda-report').click()
        expect(page.locator('#eda-report-modal')).to_be_visible()
        expect(page.locator('#eda-report-content')).to_contain_text('sales')
        page.locator('#eda-report-close').click()
        page.locator('#logout-btn').click() if page.locator('#logout-btn').is_visible() else page.goto('http://127.0.0.1:5067/app')
        # New isolated session for failure cases and mobile rendering.
        context=browser.new_context(viewport={'width':390,'height':844})
        mobile=context.new_page()
        mobile.on('pageerror',lambda err:errors.append(str(err)))
        mobile.goto('http://127.0.0.1:5067/app')
        expect(mobile.locator('#loading-overlay')).to_be_hidden()
        mobile.screenshot(path=str(shots/'aistora-login-mobile.png'),full_page=True)
        assert mobile.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
        mobile.locator('#auth-email').fill('smoke@example.com')
        mobile.locator('#auth-password').fill('launch-test-password')
        mobile.route('**/api/login',lambda route:route.fulfill(status=503,content_type='text/html',body='<h1>Upstream unavailable</h1>'))
        mobile.locator('#auth-submit-btn').click()
        expect(mobile.locator('#auth-error-message')).to_contain_text('temporarily unavailable')
        expect(mobile.locator('#auth-submit-btn')).to_be_enabled()
        mobile.unroute('**/api/login')
        mobile.route('**/api/login',lambda route:route.fulfill(status=429,headers={'Retry-After':'60'},json={'success':False,'error':'Too many attempts.'}))
        mobile.locator('#auth-submit-btn').click()
        expect(mobile.locator('#auth-error-message')).to_contain_text('1 minute')
        mobile.unroute('**/api/login')
        mobile.route('**/api/login',lambda route:route.abort())
        mobile.locator('#auth-submit-btn').click()
        expect(mobile.locator('#auth-error-message')).to_contain_text('Check your connection')
        mobile.unroute('**/api/login')
        mobile.locator('#auth-forgot-password').click()
        expect(mobile.locator('#auth-error-title')).to_have_text('Recovery unavailable')
        mobile.goto('http://127.0.0.1:5067/')
        assert mobile.evaluate('document.documentElement.scrollHeight > window.innerHeight')
        assert mobile.evaluate('getComputedStyle(document.body).overflowY') == 'auto'
        assert not errors,errors
        print(json.dumps({'result':'passed','checks':['registration via Enter','mode labels','wrong-password persistence','password visibility','login','workspace creation','CSV upload','deterministic EDA','pipeline controls hidden','mobile layout','HTML server failure','429 feedback','network failure','recovery availability','landing scroll'],'javascript_errors':errors,'screenshots':str(shots)}))
        browser.close()
finally:
    server.shutdown()
