{#- Every telemetry event the app or the pipeline emitted, one row each. -#}
{% set pattern = lake_path('events/*/*/*.jsonl.gz') %}
{% set columns = {
    'event': 'VARCHAR',
    'ts': 'TIMESTAMP',
    'host': 'VARCHAR',
    'project_id': 'BIGINT',
    'user_id': 'BIGINT',
    'dataset': 'VARCHAR',
    'load_id': 'VARCHAR',
    'request_id': 'VARCHAR',
    'status': 'VARCHAR',
    'stage': 'VARCHAR',
    'mode': 'VARCHAR',
    'source': 'VARCHAR',
    'tool': 'VARCHAR',
    'routing_tier': 'VARCHAR',
    'model': 'VARCHAR',
    'error_type': 'VARCHAR',
    'duration_ms': 'BIGINT',
    'turns': 'BIGINT',
    'tool_calls': 'BIGINT',
    'input_tokens': 'BIGINT',
    'output_tokens': 'BIGINT',
    'estimated_cost_usd': 'DOUBLE',
    'verification_passed': 'BOOLEAN',
    'rows_in': 'BIGINT',
    'rows_out': 'BIGINT',
    'rows_rejected': 'BIGINT',
    'raw_bytes': 'BIGINT',
    'quality_status': 'VARCHAR'
} %}

{% if lake_has_files(pattern) %}
select
    event,
    ts,
    host,
    project_id,
    user_id,
    dataset,
    load_id,
    request_id,
    status,
    stage,
    mode,
    source,
    tool,
    routing_tier,
    model,
    error_type,
    duration_ms,
    turns,
    tool_calls,
    input_tokens,
    output_tokens,
    estimated_cost_usd,
    verification_passed,
    rows_in,
    rows_out,
    rows_rejected,
    raw_bytes,
    quality_status,
    cast(ts as date) as dt
from {{ read_lake_json(pattern, columns) }}
where event is not null
{% else %}
select
    cast(null as VARCHAR) as event,
    cast(null as TIMESTAMP) as ts,
    cast(null as VARCHAR) as host,
    cast(null as BIGINT) as project_id,
    cast(null as BIGINT) as user_id,
    cast(null as VARCHAR) as dataset,
    cast(null as VARCHAR) as load_id,
    cast(null as VARCHAR) as request_id,
    cast(null as VARCHAR) as status,
    cast(null as VARCHAR) as stage,
    cast(null as VARCHAR) as mode,
    cast(null as VARCHAR) as source,
    cast(null as VARCHAR) as tool,
    cast(null as VARCHAR) as routing_tier,
    cast(null as VARCHAR) as model,
    cast(null as VARCHAR) as error_type,
    cast(null as BIGINT) as duration_ms,
    cast(null as BIGINT) as turns,
    cast(null as BIGINT) as tool_calls,
    cast(null as BIGINT) as input_tokens,
    cast(null as BIGINT) as output_tokens,
    cast(null as DOUBLE) as estimated_cost_usd,
    cast(null as BOOLEAN) as verification_passed,
    cast(null as BIGINT) as rows_in,
    cast(null as BIGINT) as rows_out,
    cast(null as BIGINT) as rows_rejected,
    cast(null as BIGINT) as raw_bytes,
    cast(null as VARCHAR) as quality_status,
    cast(null as date) as dt
where false
{% endif %}
