"""initial schema: user, project, table, agent_run

Revision ID: 1d8ab2e053ae
Revises: 
Create Date: 2026-09-02 22:55:09.781508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8ab2e053ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('goal_signature', sa.String(length=800), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('routing_tier', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('result_kind', sa.String(length=30), nullable=True),
    sa.Column('result_name', sa.String(length=100), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('feedback_rating', sa.String(length=10), nullable=True),
    sa.Column('feedback_comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_user_id'), ['user_id'], unique=False)

    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('columns_schema', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_run_status'))
        batch_op.drop_index(batch_op.f('ix_agent_run_request_id'))
        batch_op.drop_index(batch_op.f('ix_agent_run_project_id'))

    op.drop_table('agent_run')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
